services:
  - type: web
    name: api
    env: python
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT "main:create_app()" --factory
    deployWaitTimeout: 300

  - type: worker
    name: worker
    env: python
    build:
      dockerfile: Dockerfile
    startCommand: python -m app.workers.csv_worker
    deployWaitTimeout: 300

jobs:
  - type: deploy
    name: migration
    env: python
    build:
      dockerfile: Dockerfile
    startCommand: python scripts/migration.py
    trigger: on-deploy