"""First schema migration

Revision ID: 28e0bf15d583
Revises: 
Create Date: 2025-09-12 16:07:32.369008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e0bf15d583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_shopify_store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'store_name'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index('idx_registered_store', 'registered_shopify_store', ['store_name'], unique=False)
    op.create_index('idx_analysis_data_id', 'analysis_data', ['id'], unique=False)
    op.create_index('idx_csv_queue_status_upload_id_progress', 'csv_queue', ['status', 'upload_id', 'progress'], unique=False)
    op.create_index('idx_excel_queue_status_upload_id_progress', 'excel_queue', ['status', 'upload_id', 'progress'], unique=False)
    op.add_column('registered_number', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_registered_number', 'registered_number', ['number'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_registered_number', table_name='registered_number')
    op.drop_column('registered_number', 'updated_at')
    op.drop_index('idx_excel_queue_status_upload_id_progress', table_name='excel_queue')
    op.drop_index('idx_csv_queue_status_upload_id_progress', table_name='csv_queue')
    op.drop_index('idx_analysis_data_id', table_name='analysis_data')
    op.drop_index('idx_registered_store', table_name='registered_shopify_store')
    op.drop_table('registered_shopify_store')
    # ### end Alembic commands ###
